### ISSUE TITLE
Wire up data service lambda function to frontend

### ISSUE THREAD

**Issue by wjbuys** [blox/blox#280]
After we have some way of calling the DataService (see #227), we should wire this up to the Frontend.

Each data service client needs the following:
- the name of the data service's Lambda function
- permissions to invoke that Lambda function
- a correctly configured JsonRpcLambdaClient that can serialize/deserialize all dataservice types.
 
### Tasks
- [x] add createEnvironment, describeEnvironment, startEnvironmentDeployment APIs
- [x] wire up DataService through spring/cloudformation
- [x] modify end-to-end tests to call frontend
- [ ] add error mapping/logging to frontend

**Comment by wjbuys** [comment]
I'm having some trouble expressing our API in swagger. If I try to structure things for the AWS IAM auth to just work, then the generated client is confusing.

The two constraints that are in tension are:
- Encoding resource names in the URL. This is needed for API Gateway's automatic authorization support. In particular, any attributes we wish to authorize on have to be part of the URL, so that it can be converted to an ARN internally.
- Providing resource properties as a JSON POST payload.

So, for example for `updateEnvironment`, the URL must contain the attributes we wish to support resource-based authorization on, in this case `/environment/{environmentName}`. However, if the swagger definition contains both a PathVariable (`environmentName`) and a request body (`UpdateEnvironmentRequest`):

```
paths:
  /v1/{cluster}/environments/{environmentName}:
    put:
      summary: "Update environment"
      description: ""
      operationId: "updateEnvironment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cluster"
        in: "path"
        required: true
        type: "string"
      - name: "environmentName"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/UpdateEnvironmentRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UpdateEnvironmentResponse"
definitions:
  UpdateEnvironmentResponse:
    type: "object"
  UpdateEnvironmentRequest:
    type: "object"
    properties:
      taskDefinition:
        type: "string"
```

then the generated client will take a request that looks like:

```
class UpdateEnvironmentRequest {
  String cluster
  String environmentName
  UpdateEnvironmentRequest updateEnvironmentRequest
}
```

This looks like a bug in the generator, since `UpdateEnvironmentRequest` is now a recursive reference. However, even if we rename the body type to no longer conflict with the generated request class (e.g. to just `Environment`), then the generated client will still generate a separate property for the body object.

**Comment by wjbuys** [comment]
Ah, I've figured it out. Looks like we can pass `flattenRequests=true,flattenResponses=true` as parameters to the `aws apigateway get-sdk` command, and it will remove the superfluous wrapper object.

**Comment by wjbuys** [comment]
Now I'm trying to figure out how to return modeled exceptions. There doesn't seem to be clear docs on how throwing exceptions from Spring's handler classes gets mapped to response entities. The best example I could find is [here](https://github.com/kongchen/swagger-maven-plugin/blob/02c0b48758278de493803855d51d0fd2d0bebb6d/src/test/java/com/wordnik/springmvc/PetResource.java#L72). However, that doesn't create typed exceptions in the swagger output, and so the generated client would not have any typed exceptions either.

On the other hand, if I specify a real exception type using something like:

```
  @ApiResponses(
      @ApiResponse(
        code = 404,
        message = "environment not found",
        response = EnvironmentNotFoundError.class
      ))
```

that generates a typed exception, but also includes private fields from the Exception supertype:

```
  EnvironmentNotFoundException:
    type: "object"
    properties:
      cause:
        $ref: "#/definitions/Throwable"
      stackTrace:
        type: "array"
        items:
          $ref: "#/definitions/StackTraceElement"
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      localizedMessage:
        type: "string"
      suppressed:
        type: "array"
        items:
          $ref: "#/definitions/Throwable"
  StackTraceElement:
    type: "object"
    properties:
      methodName:
        type: "string"
      fileName:
        type: "string"
      lineNumber:
        type: "integer"
        format: "int32"
      className:
        type: "string"
      nativeMethod:
        type: "boolean"
  Throwable:
    type: "object"
    properties:
      cause:
        $ref: "#/definitions/Throwable"
      stackTrace:
        type: "array"
        items:
          $ref: "#/definitions/StackTraceElement"
      message:
        type: "string"
      localizedMessage:
        type: "string"
      suppressed:
        type: "array"
        items:
          $ref: "#/definitions/Throwable"
```

**Comment by wjbuys** [comment]
More problems: when using a controller-wide `RequestMapping` to set up a common URL pattern for all calls, I have to include an explicit `"/"` in the path for the `RequestMapping` on the handler method:

```java
@RequestMapping(path = "/v1/{cluster}/environments")
class EnvironmentController {
  @RequestMapping(path="/", method = RequestMethod.POST)
  public CreateEnvironmentResponse createEnvironment(...) { ... }
}
```

This generates a URI path with a trailing `"/"` in the swagger yaml that looks like:
```
paths:
  /v1/{cluster}/environments/:
    post:
      operationId: "createEnvironment"
      # ...
```

However, the client generated from the generated swagger seems to omit the trailing `"/"` from the requests it makes, and the stricter Spring MVC router doesn't match `/v1/{cluster}/environments` to the `/v1/{cluster}/environments/` route:

```
INFO RequestMappingHandlerMapping:Mapped "{[/v1/{cluster}/environments/],methods=[POST],consumes=[application/json],produces=[application/json]}" onto public com.amazonaws.blox.frontend.models.wrappers.CreateEnvironmentResponse com.amazonaws.blox.frontend.controllers.EnvironmentController.createEnvironment(...
DEBUG DispatcherServlet:DispatcherServlet with name 'aws-servless-java-container' processing POST request for [/v1/default/environments]
DEBUG RequestMappingHandlerMapping:Looking up handler method for path /v1/default/environments
DEBUG RequestMappingHandlerMapping:Did not find handler method for [/v1/default/environments]
```

However, if I replace `path = "/"` with `path = ""`, then the swagger generator doesn't generate a definition for the method at all...

**Comment by wjbuys** [comment]
The above issue arises from [this line in the swagger generator](https://github.com/kongchen/swagger-maven-plugin/blob/master/src/main/java/com/github/kongchen/swagger/docgen/reader/SpringMvcApiReader.java#L422). It looks like omitting the path or value completely might trigger the right code path here.

**Comment by wjbuys** [comment]
That works, omitting the `path = ""` attribute property completely triggers the correct swagger generation.

**Comment by wjbuys** [comment]
I'm looking into exception mapping again. It looks like we can use non-exception error classes to generate the right swagger for exception outputs. However, it looks like the client code that's generated discards the name of the declared exception type, and uses the general name for the HTTP status code instead. For example, I've got this swagger definition:

```yaml
paths:
  # ...
    post:
      # ...
      responses:
        # ...
        400:
          description: "Invalid parameter"
          schema:
            $ref: "#/definitions/InvalidParameterError"
#...
definitions:
  # ...
  InvalidParameterError:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"

```

But the client code generated from this only has a generic BadRequestException:

```java
@Generated("com.amazonaws:aws-java-sdk-code-generator")
public class BadRequestException extends com.amazonaws.blox.model.BloxException {
    private static final long serialVersionUID = 1L;

    private Integer code;
    // ...
}
```

**Comment by wjbuys** [comment]
It looks like this is a limitation of the current SDK generation code. I'm following up internally with the team responsible. For now, we'll have to deal with the mismatched exception classes.

**Comment by wjbuys** [comment]
Apparently this limitation is intentional, and only one client-side Exception type per HTTP status code is supported. However, if we want to use custom-named exceptions, there's an undocumented parameter to the SDK generator that we can use to customize the exception name to match what's in our Swagger model:

> `exceptionForXXX`: Specify a 4xx or 5xx status code in the parameter name, and provide a value to rename the exception type (e.g. exceptionFor400=BogusInputException).

**Comment by wjbuys** [comment]
Just recording some more background here on why we have a mix of `*Request` POJOs and arguments with simple types on the frontend handlers, for example:

https://github.com/wjbuys/blox/blob/dcc96ab5a9d5d4d36001db984acab2aab47c4075/frontend-service/src/main/java/com/amazonaws/blox/frontend/operations/CreateEnvironment.java#L45-L55

Even though the Spring MVC controller supports annotating fields of a POJO with e.g. `@PathVariable` and will bind the appropriate path variable to that field of the POJO, the Swagger generator we're using doesn't support mixing that with a POJO that's deserialized from the request body.

**Comment by wjbuys** [comment]
We're doing more fine-grained tracking on our team sprint board, resolving this for now.
